services:
  - type: web
    name: rust-compute-demo
    env: rust
    plan: free
    autoDeploy: true
    rootDir: .
    buildCommand: cargo build --release
    startCommand: ./target/release/rust-compute-demo
    envVars:
      - key: RUST_LOG
        value: info
    healthCheckPath: "/"
